### ISSUE TITLE
Text output

### ISSUE THREAD

**Issue by gonzalezm** [has2k1/gnuplot_kernel#11]
This kernel is great. Is it possible to suppress the text output of the cells? In the output of each cell there is not only the plot but also a copy of all the commands being run (screenshot attached).
Thanks in advance
 
![textoutput](https://user-images.githubusercontent.com/7226519/35636457-eee9eb02-068f-11e8-9165-664d7082649d.png)

**Comment by has2k1** [comment]
What version of gnuplot are you using. I do not get the text output on v5.2.2.

**Comment by gonzalezm** [comment]
Thanks for your reply. I was using version 5.0. I upgraded to v5.2.2 and the result is the same. I am using Python 3 with Anaconda.

**Comment by has2k1** [comment]
What version of the dependency package `metakernel` do you have installed?

**Comment by gonzalezm** [comment]
I am using metakernel version 0.20.14 and I am using Anaconda.

**Comment by adsche** [comment]
Were you able to resolve this issue?
I'm experiencing the same with metakernel v. 0.20.14 from conda_forge and gnuplot 4.6 patchlevel 2 (CentOS).

Let me know if you need any more data to pinpoint this...

**Comment by gonzalezm** [comment]
Unfortunately I haven't been able to solve this issue, which is quite
annoying when you use many instructions to perform a plot. If you have any
hint to solve this please let me know.



2018-08-17 10:42 GMT-03:00 adsche <notifications@github.com>:

**Comment by has2k1** [comment]
I put out new version of `gnuplot_kernel` recently and during the testing I could not replicate this issue.

**Comment by adsche** [comment]
Alright :(
has2k1, could you also tell me the gnuplot and metakernel version that you were using for testing? What OS are you testing on?

I'm going to try to investigate a bit more.

**Comment by has2k1** [comment]
The specs are:

- gnuplot: 5.2.4
- metakernel: 0.20.14
- OS: Arch Linux

**Comment by gonzalezm** [comment]
Hi,

My specs are:
gnuplot 5.2.2
metakernel 0.20.14
OS: Ubuntu

The problem is still there.

Thanks for trying to solve the issue.

2018-08-20 10:59 GMT-03:00 Hassan Kibirige <notifications@github.com>:

**Comment by gonzalezm** [comment]
I can confirm that this problem is not present in Antergos using gnuplot
5.2.4 and metakernel 0.20.14

2018-08-21 9:30 GMT-03:00 Manu Gonzalez <elhombrecitodelazulejo@gmail.com>:

**Comment by has2k1** [comment]
So this bug only chooses to haunt select systems! At least it is not going after the users.

**Comment by adsche** [comment]
What python versions were y'all using? I'm using 3.6.5.

**Comment by gonzalezm** [comment]
I'm using Python 3.6.3

**Comment by razimantv** [comment]
Same issue on Ubuntu 18.04.1 LTS
Versions:
Python 3.6.6
gnuplot 5.2 patchlevel 2
gnuplot-kernel 0.3.0 (installed using pip3)
metakernel 0.20.14 (using pip3)

**Comment by has2k1** [comment]
While I do not know why this bug affected some installations, we now clobber any output from gnuplot if it matches the input. If there aren't any unintended consequences then the solution shall stand.
