### ISSUE TITLE
Configure the repo to support running in MyBinder

### ISSUE THREAD

**Issue by psychemedia** [has2k1/gnuplot_kernel#15]
It would be good to be able to run the notebooks that demo this kernel via MyBinder.

I'm guessing that if there was a pattern for Binderising one kernel based on Metakernel, it would work for all kernels where a container could be built to include the application being wrapped as a kernel application?

**Comment by has2k1** [comment]
I do not know what MyBinder is.

**Comment by psychemedia** [comment]
@has2k1 Its a service that will build and run a Docker container based on the contents of a Github repository, along with a Jupyter notebook server, which means that folk can try running your code at the click of a button:

https://mybinder.org/
https://binderhub.readthedocs.io/en/latest/

The repo can then also be used with [`repo2docker`](https://repo2docker.readthedocs.io/en/latest/) to launch a local Docker container built therefrom, also including a notebook server.
