### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by kaihendry** [has2k1/gnuplot_kernel#23]
How come SVG doesn't appear to work here?

https://s.natalian.org/2020-07-09/svg-gnuplot.png

```
# git rev-list --count master
$commits << EOD
gecko 716280
webkit 226748
blink 400000
EOD

set terminal svg
set yrange [0:*]      # start at zero, find max from the data
set boxwidth 0.5      # use a fixed width for boxes
unset key             # turn off all titles
set style fill solid  # solid color boxes
set ytics format "%.0s%c" #  will generate labels 100k 200k 300k ... 1M
set title 'commits'
plot '$commits' using 2:xtic(1) with boxes
```

Sidenote: Learned about this project via Lee Philips of the gnuplot 5 book. The ctrl+enter workflow that Jupyter Notebook in a browser offers is far easier than working on the command line. Is this experience offered on a public URL somewhere? Or can it be? (happy to host)

**Comment by has2k1** [comment]
Use inline magic to set the inline plotting to svg. e.g.
```
%gnuplot inline svg
plot ...
```

**Comment by kaihendry** [comment]
Can't quite understand what I need here: https://s.natalian.org/2020-07-09/svg-jplot.mp4 

hmm, bit confused by the magic https://s.natalian.org/2020-07-09/magic.mp4

**Comment by has2k1** [comment]
Do not use 'set'. Use the exact line below starting with the percent.

%gnuplot inline svg

**Comment by has2k1** [comment]
Put the line at the top of the cell, or in it's own cell.

**Comment by kaihendry** [comment]
Thank you! <img src=https://s.natalian.org/2020-07-10/1594347597_2560x1440.png>
