### ISSUE TITLE
Retrieve CSV from URL

### ISSUE THREAD

**Issue by kaihendry** [has2k1/gnuplot_kernel#24]
Greatly enjoying the IDE for gnuplot iterations, however how do I fetch data from a URL?

For example https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-22-2020.csv ?

I know how it works in python roughly, but not this kernel.

**Comment by has2k1** [comment]
See how the %%shell block magic is used in the example notebook,
https://github.com/has2k1/gnuplot_kernel/blob/master/examples/gnuplot-kernel.ipynb
.

You can use wget or curl or any other command that downloads files.

**Comment by kaihendry** [comment]
Be good if you could have an example where the curl stdouts into some variable that I can plot off the bat! Thanks again!

**Comment by has2k1** [comment]
I don't think you can download into a variable. You have to download to
file then use the file in gnuplot.

**Comment by kaihendry** [comment]
Yes, you're right, it needs to be in a file to be used. Thank you!
