### ISSUE TITLE
State of the cell is unclear

### ISSUE THREAD

**Issue by kaihendry** [has2k1/gnuplot_kernel#25]
I noticed when I remove lines and ctrl+enter (iterate), it still appears to have the previous commands in effect.

This is very confusing and results in situations where I've after I've refactored, I don't have a working gnuplot.

https://s.natalian.org/2020-07-10/removing-lines.mp4

Any tips please?

**Comment by has2k1** [comment]
See %reset, %%reset (magics) and the reset (gnuplot command) in the example
notebook
https://github.com/has2k1/gnuplot_kernel/blob/master/examples/gnuplot-kernel.ipynb

In this case just end the cell with the 'reset' command. This is just like
using gnuplot on the command line were you either unset specific settings
of reset all plot specific settings at once,
http://www.bersch.net/gnuplot-doc/reset.html.

**Comment by kaihendry** [comment]
Thank you https://s.natalian.org/2020-07-11/concern.mp4

Still find it a little confusing, but I think this is just the way Jupyter Notebook works

**Comment by kaihendry** [comment]
I'm still very confused by the https://s.natalian.org/2020-07-11/reset.mp4 logic...

**Comment by has2k1** [comment]
Forget about %reset and %%reset.

Use 'reset' (no percent signs), the gnuplot command.

**Comment by kaihendry** [comment]
Ok, that appears to work. Though darn, quite easy to get into a bad state.

**Comment by kaihendry** [comment]
Found it doesn't work for `set colors`..

https://s.natalian.org/2020-07-11/reset-color.mp4
