### ISSUE TITLE
Warning about prompt at each cell

### ISSUE THREAD

**Issue by agiliopadua** [has2k1/gnuplot_kernel#31]
Hi.
The kernel runs fine (macOS, conda) but I get this message after running each cell:

        Warning: The prompt is currently set to '2004hgnuplot> '
        Out[*]: ?2004l

Thx.

**Comment by has2k1** [comment]
What is the gnuplot prompt when you use it in the terminal?

**Comment by agiliopadua** [comment]
It's
gnuplot>

**Comment by has2k1** [comment]
Can you confirm that it is the same gnuplot that is used by the kernel. i.e. use the full path to `gnuplot` that is returned by this command.

```sh
$ python -c 'from metakernel import pexpect; print(pexpect.which("gnuplot"))'
/usr/bin/gnuplot
```

**Comment by agiliopadua** [comment]
Yup. I only have one installed (5.4.1 from Homebrew):
/usr/local/bin/gnuplot

**Comment by has2k1** [comment]
It seems like there is a weird character(s) before `gnuplot>`, because when `gnuplot>` is right-stripped from  `2004hgnuplot>`, the result is `?2004l`!

Have you run the code anywhere else online, because there is a similar issue [here](https://home.hirosaki-u.ac.jp/heroic-2020/1565/) and it looks to have appeared in the last day.

**Comment by agiliopadua** [comment]
This seems to be an escape sequence for bracketed paste mode (something I had not heard of before). I don't know how your kernel interacts with the gnuplot process (using a shell?)

**Comment by agiliopadua** [comment]
Just reinstalled gnuplot recompiling from source as in the page you pointed to. The issue is with the readline library. No I no longer have those escape characters polluting the output.

**Comment by has2k1** [comment]
> This seems to be an escape sequence for bracketed paste mode (something I had not heard of before). I don't know how your kernel interacts with the gnuplot process (using a shell?)

First time I am hearing of `bracketed paste mode` too. From a somewhat long memory, the underlying libraries just spawn `gnuplot` as a separate process; no intermediary shell. 

> Now I no longer have those escape characters polluting the output.

Great.

**Comment by thosef** [comment]
Before compilation of the gnuplot executable, it needs to be configured to use its own readline library, with
./configure --with-readline=builtin
Otherwise, at least on linux systems, GNU readline library is compiled in, which adds these additional characters.
