### ISSUE TITLE
not work on Mac, can not display image~~

### ISSUE THREAD

**Issue by xtchenhui** [has2k1/gnuplot_kernel#4]
An unknown error occured. Failed to read and display image file from gnuplot.
Out[4]:
Terminal type set to 'unknown'
                      ^
         unknown or ambiguous terminal type; type just 'set terminal' for a list

**Comment by has2k1** [comment]
I do not use a a Mac so I am unable to verify whether this issue affects all Macs. However, I think it may be local, probably due a missing the `cairopng` backend.

Set the terminal to one that is available on your system. Also see the example [notebook](https://github.com/has2k1/gnuplot_kernel/blob/master/examples/gnuplot-kernel.ipynb) on how to change the terminal from within the IPython session.

**Comment by nleclercq** [comment]
I confirm that gnuplot-kernel 0.2.3 works on my mac:
```
sudo port install gnuplot     (mac ports)
pip install gnuplot_kernel   (no condo package soi I used pip)
conda install metakernel  (use pip if you don't have anaconda)
```
done!
