### ISSUE TITLE
kernel.json missing

### ISSUE THREAD

**Issue by oni303** [has2k1/gnuplot_kernel#5]
hi,

I just tried to install the kernel as you described. 
Result: no GnuPlot kernel in jupyter notebook.

After I added a kernel.json in usr/local/share/jupyter/kernels/gnuplot_kernel it works fine.
Content of kernel.json:
{"argv": ["/usr/bin/python", "-m", "gnuplot_kernel", "-f", "{connection_file}"], "display_name": "GnuPlot", "language": "gnuplot", "name": "gnuplot_kernel"}

regrads
oni

**Comment by has2k1** [comment]
Though you have it working, can you follow the instructions [in this comment](
https://github.com/has2k1/gnuplot_kernel/issues/1#issuecomment-189754560) and post the result.

Also what O.S. are you using.

**Comment by oni303** [comment]
with my kernel.json the result is:
```
{'gnuplot_kernel': '/usr/local/share/jupyter/kernels/gnuplot_kernel',
 'metakernel_python': '/usr/local/share/jupyter/kernels/metakernel_python',
 'python2': '/home/vonzeng/.local/share/jupyter/kernels/python2',
 'python3': '/usr/local/share/jupyter/kernels/python3'}
```

with out the kernel.json:
```
{'metakernel_python': '/usr/local/share/jupyter/kernels/metakernel_python',
 'python2': '/home/vonzeng/.local/share/jupyter/kernels/python2',
 'python3': '/usr/local/share/jupyter/kernels/python3'}
```

I am using Fedora Linux 23 with python 3.4 and gnuplot_kernel 0.2.1 installed via pip

Ok I just tried:
```
pip uninstall gnuplot_kernel
pip install --upgrade --no-cache-dir git+https://github.com/has2k1/gnuplot_kernel.git@master
```
after that I got a gnuplot kernel:

```
{'gnuplot': '/usr/local/share/jupyter/kernels/gnuplot',
 'metakernel_python': '/usr/local/share/jupyter/kernels/metakernel_python',
 'python2': '/home/vonzeng/.local/share/jupyter/kernels/python2',
 'python3': '/usr/local/share/jupyter/kernels/python3'}
```

**Comment by chrisberkhout** [comment]
I'm on ArchLinux. I initially installed with `sudo pip install gnuplot_kernel` and only saw these:
```
{'python3': '/usr/lib/python3.5/site-packages/ipykernel/resources',
 'python2': '/usr/share/jupyter/kernels/python2',
 'ir': '/home/chris/.local/share/jupyter/kernels/ir'}
```
After reinstalling from `master` as above, it works.

**Comment by has2k1** [comment]
I still have no idea what is causing this bug. The same code is being installed.

To others who run into this issue, please do a `pip list` before and after you install from master. That is;

```bash
$ pip install gnuplot_kernel
# Assuming the above command does not work
$ pip list
$ pip install --upgrade --no-cache-dir git+https://github.com/has2k1/gnuplot_kernel.git@master
# Assuming the above command works
$ pip list
```

**Comment by wuebbel** [comment]
I know this issue is ancient, but anyway: I issued "pip install gnuplot_kernel" in an up to date conda environment. 

Created no gnuplot_kernel directory. Doing the pip list-thing from above changed nothing. "python3 -m gnuplot_kernel install" tried to create a python3-directory and did not help either.

Manually creating gnuplot_kernel and creating the .json-File as proposed above solved the problem.

**Comment by has2k1** [comment]
The installation has been altered in the current version, and I think this issue should be resolved.
