### ISSUE TITLE
gnuplot's data blocks not supported under gnuplot_kernel?

### ISSUE THREAD

**Issue by esternin** [has2k1/gnuplot_kernel#9]
In a Jupyter notebook, this produces no output, times out after 30s (while the equivalent works fine directly in gnuplot):
```
%load_ext gnuplot_kernel
%gnuplot inline pngcairo
```
```
%%gnuplot
$DATA <<EOD
# x y
0.5 3
0.7 4
1.5 5
2   6
EOD
plot $DATA
stats $DATA
```
Similar timeout if the entire kernel is set to gnuplot (not magic extension, but the kernel itself). 
Installed via 
  `  pip install --upgrade --no-cache-dir git+https://github.com/has2k1/gnuplot_kernel.git@master`

**Comment by has2k1** [comment]
Thanks for filing this. When I created the kernel my understanding of gnuplot was only a few days, I did not know about data blocks. And I have not used it at all ever since.

Sorry, I cannot promise when I look into this.

**Comment by esternin** [comment]
You closed this, and I never had a chance to thank you for fixing this.

THANKS!
